// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "password": "كلمة المرور",
  "phone": "رقم الهاتف",
  "login": "تسجيل الدخول",
  "cancel": "إلغاء",
  "confirm": "تأكيد",
  "done": "تم",
  "loading": "جارٍ التحميل",
  "dismiss": "رفض",
  "success": "نجاح",
  "info": "معلومة",
  "error": "خطأ",
  "warning": "تحذير",
  "about": "حول",
  "option": "اختياري",
  "somethingWrong": "حدث خطأ ما! يرجى المحاولة مرة أخرى",
  "unknownError": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  "noInternetConnection": "لا يوجد اتصال بالإنترنت، حاول مرة أخرى لاحقًا",
  "noItems": "لا توجد عناصر",
  "badRequest": "طلب غير صالح",
  "unauthorised": "غير مصرح",
  "notFound": "غير موجود",
  "invalidInput": "الادخال غير صالح",
  "serverError": "خطأ في الخادم",
  "cacheError": "خطأ في الذاكرة المؤقتة",
  "parseDataError": "حدث خطأ في بيانات الاستجابة، يرجى المحاولة مرة أخرى",
  "permissionDenied": "تم رفض الإذن المطلوب، يرجى السماح بالوصول",
  "permissionPermanentlyDenied": "الإذن مرفوض نهائياً، افتح إعدادات التطبيق لتفعيله",
  "sessionTimedOut": "انتهت صلاحية الجلسة",
  "sessionRevoked": "تم تسجيل خروجك من جهاز آخر",
  "notPrimaryDevice": "لا تملك صلاحية تسجيل خروج الأجهزة الأخرى",
  "deviceNotFound": "الجهاز غير موجود أو تم إلغاؤه مسبقاً",
  "invalidPassword": "كلمة مرور مطلوبة",
  "invalidPasswordLength": "يجب ان تكون كلمة المرور على الأقل ٨ أحرف وعلى الأكثر ٣٠ حرف",
  "passwordValidationError": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل وحرف واحد على الأقل",
  "invalidEmailAddress": "عنوان البريد الإلكتروني غير صالح",
  "welcomeBack": "مرحبًا بك مرة أخرى",
  "loginToYourAccount": "تسجيل الدخول إلى حسابك",
  "eMail": "البريد الإلكتروني",
  "typeEmail": "اكتب بريدك الإلكتروني",
  "forgotPassword": "هل نسيت كلمة المرور؟",
  "dontHaveAccount": "ليس لديك حساب؟",
  "continueGuest": "استمر كضيف",
  "SignUp": "اشتراك",
  "justNow": "الآن",
  "minAgo": "دقيقة مضت",
  "hAgo": "ساعة مضت",
  "dAgo": "يوم مضى",
  "wAgo": "أسبوع مضى",
  "moAgo": "شهر مضى",
  "yAgo": "سنة مضت",
  "appAppearance": "مظهر التطبيق",
  "theme": "الثيم",
  "widgetLibraryTitle": "تجربة الويدجتات والإضافات",
  "toast": "توست",
  "toastMessage": "رسالة توست",
  "toastSuccess": "توست نجاح",
  "toastError": "توست خطأ",
  "snackbar": "سناك بار",
  "dialog": "ديالوج",
  "dialogContent": "محتوى ديالوج",
  "title": "عنوان",
  "sheetContent": "محتوى الشيت",
  "bottomSheet": "بوتم شيت",
  "states": "حالات",
  "emptyState": "حالة فارغة",
  "errorRetry": "خطأ + إعادة",
  "noInternet": "لا إنترنت",
  "placeholders": "عناصر وهمية",
  "feedback": "الرجع",
  "images": "صور",
  "layout": "تخطيط",
  "misc": "متنوع",
  "indicators": "مؤشرات",
  "dateMaterial": "تاريخ (ماتريال)",
  "dateCalendar": "تاريخ (تقويم)",
  "timeMaterial": "وقت (ماتريال)",
  "retry": "إعادة المحاولة",
  "updateAvailableTitle": "تحديث متاح",
  "updateAvailableMessage": "يتوفر إصدار جديد من التطبيق. يُنصح بالتحديث.",
  "updateNow": "تحديث",
  "later": "لاحقاً",
  "reconnecting": "جاري الاتصال...",
  "syncing": "جاري المزامنة...",
  "syncPattern": "نمط المزامنة",
  "goOffline": "العمل دون اتصال",
  "goOnline": "العودة إلى الاتصال",
  "syncQueueEmpty": "صف المزامنة فارغ",
  "localStorage": "التخزين المحلي",
  "serverState": "حالة السيرفر",
  "productStock": "المخزون",
  "connectionOnline": "متصل - المزامنة التلقائية نشطة",
  "connectionOffline": "غير متصل - الحفظ محلياً",
  "tapToDisconnect": "اضغط لقطع الاتصال",
  "tapToReconnect": "اضغط للاتصال",
  "syncStatusPending": "في الانتظار",
  "syncStatusProcessing": "جاري الرفع",
  "syncStatusSynced": "مزامن",
  "syncStatusFailed": "فاشل",
  "syncStatusOffline": "غير متصل",
  "queueSectionTitle": "طابور المزامنة",
  "eventLogTitle": "سجل الأحداث",
  "settings": "الإعدادات",
  "appearance": "المظهر",
  "language": "اللغة",
  "notifications": "الإشعارات",
  "enableNotifications": "تفعيل الإشعارات",
  "appInfo": "حول التطبيق",
  "appVersion": "إصدار التطبيق",
  "clearCache": "مسح الذاكرة المؤقتة",
  "cacheClearedSuccessfully": "تم مسح الذاكرة المؤقتة",
  "themeLight": "فاتح",
  "themeDark": "داكن",
  "themeSystem": "تلقائي (حسب النظام)",
  "typography": "الخطوط",
  "discardChangesTitle": "تجاهل التغييرات؟",
  "discardChangesMessage": "لديك تغييرات غير محفوظة. هل تريد المغادرة؟",
  "profile": "الملف الشخصي",
  "editProfile": "تعديل الملف الشخصي",
  "birthdate": "تاريخ الميلاد",
  "address": "العنوان",
  "send": "إرسال",
  "backToLogin": "العودة لتسجيل الدخول",
  "forgotPasswordHint": "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين كلمة المرور",
  "checkYourEmail": "تحقق من بريدك الإلكتروني",
  "resetLinkSentTo": "تم إرسال رابط إعادة التعيين إلى",
  "firstName": "الاسم الأول",
  "lastName": "الاسم الأخير",
  "confirmPassword": "تأكيد كلمة المرور",
  "passwordMismatch": "كلمة المرور غير متطابقة",
  "save": "حفظ",
  "add": "إضافة",
  "delete": "حذف",
  "apply": "تطبيق",
  "reset": "إعادة تعيين",
  "filter": "فلتر",
  "sortBy": "ترتيب حسب",
  "deleteConfirmTitle": "تأكيد الحذف",
  "deleteConfirmMessage": "هل أنت متأكد من حذف هذا العنصر؟",
  "addedSuccessfully": "تمت الإضافة بنجاح",
  "updatedSuccessfully": "تم التحديث بنجاح",
  "deletedSuccessfully": "تم الحذف بنجاح",
  "fieldRequired": "هذا الحقل مطلوب",
  "invalidEmail": "البريد الإلكتروني غير صحيح",
  "passwordLength": "كلمة المرور يجب أن تكون بين 8 و 30 حرفاً",
  "passwordWeak": "كلمة المرور ضعيفة",
  "invalidPhone": "رقم الهاتف غير صحيح",
  "logOut": "تسجيل الخروج",
  "logoutConfirmTitle": "تسجيل الخروج؟",
  "logoutConfirmMessage": "هل أنت متأكد من تسجيل الخروج؟",
  "exitAppTitle": "الخروج من التطبيق؟",
  "exitAppMessage": "هل أنت متأكد من الخروج من التطبيق؟",
  "tabHome": "الرئيسية",
  "tabProfile": "الحساب",
  "tabSettings": "الإعدادات",
  "homeSubtitle": "استكشف إمكانيات التطبيق",
  "quickAccess": "وصول سريع",
  "widgetCatalogTitle": "معرض الويدجتات",
  "widgetCatalogSubtitle": "تصفح جميع مكونات الواجهة المتاحة",
  "users": "المستخدمون",
  "usersSubtitle": "تصفح قائمة المستخدمين",
  "testDashboard": "لوحة التجربة",
  "testFormsDemoTitle": "تجربة النماذج",
  "testFormsSubtitle": "Validation · Controllers · Submit",
  "testStatesDemoTitle": "تجربة الحالات",
  "testStatesSubtitle": "Loading · Error · Empty · NoInternet",
  "testThemeDemoTitle": "الألوان والخطوط",
  "testThemeSubtitle": "لوحة الألوان ومقياس النصوص",
  "fullName": "الاسم الكامل",
  "submitSuccess": "تم الإرسال بنجاح",
  "selectState": "اختر الحالة",
  "colorPalette": "لوحة الألوان",
  "maintenance": "قيد الصيانة",
  "testSettingsDemoTitle": "الإعدادات",
  "testSettingsSubtitle": "اللغة · الثيم · الخطوط",
  "feedbackStyle": "نمط التغذية الراجعة",
  "testFormValidationTitle": "تحقق النماذج",
  "testFormValidationSubtitle": "الحالات · الحماية · التغذية المرئية",
  "autoValidate": "تحقق تلقائي",
  "submitGuard": "حماية الإرسال",
  "formStateLabel": "حالة النموذج",
  "formValid": "صالح",
  "formInvalid": "غير صالح",
  "simulateApiError": "محاكاة خطأ API",
  "doubleSubmitBlocked": "الإرسال المزدوج محظور!",
  "beforeFirstSubmit": "قبل أول إرسال",
  "testPaginationDemoTitle": "عرض الترقيم",
  "testPaginationSubtitle": "أنماط التحميل · أوضاع العرض",
  "loadingStyle": "نمط التحميل",
  "displayMode": "وضع العرض",
  "pageSize": "حجم الصفحة",
  "delayMs": "التأخير",
  "errorChance": "احتمال الخطأ",
  "shimmerList": "شيمر قائمة",
  "shimmerGrid": "شيمر شبكة",
  "skeletonRows": "هيكل صفوف",
  "spinnerStyle": "دوار",
  "viewList": "قائمة",
  "viewGrid2": "شبكة 2",
  "viewGrid3": "شبكة 3",
  "simulateError": "محاكاة خطأ",
  "simulateEmpty": "محاكاة فارغ",
  "page": "صفحة",
  "items": "عناصر",
  "pageLoadingStyle": "مؤشر تحميل الصفحة",
  "loadingMore": "جارٍ تحميل المزيد…",
  "testCrudDemoTitle": "محاكاة CRUD",
  "testCrudSubtitle": "إضافة · تعديل · حذف · تراجع",
  "addProduct": "إضافة منتج",
  "editProduct": "تعديل منتج",
  "productName": "اسم المنتج",
  "productPrice": "السعر",
  "productCategory": "الفئة",
  "simulateServerError": "محاكاة خطأ الخادم",
  "optimisticUpdates": "تحديثات تفاؤلية",
  "eventLog": "سجل الأحداث",
  "clearLog": "مسح السجل",
  "rollbackApplied": "تم التراجع!",
  "noEventsYet": "لا أحداث بعد",
  "testPredictiveBackTitle": "الرجوع التنبؤي",
  "testPredictiveBackSubtitle": "PopScope · حراسة الرجوع · Android 14+",
  "manifestEnabled": "AndroidManifest مُهيَّأ",
  "backFree": "رجوع حر",
  "backFreeDesc": "canPop: true — النظام يتحكم بالرجوع، المعاينة التنبؤية تعمل في Android 14+",
  "backConfirm": "تأكيد عند الرجوع",
  "backConfirmDesc": "canPop: false — يعترض الرجوع ويعرض حوار تأكيد",
  "backDirtyGuard": "حراسة النموذج المعدَّل",
  "backDirtyGuardDesc": "canPop: false — يمنع الرجوع فقط عند وجود تغييرات غير محفوظة",
  "pressBackToTest": "اضغط رجوع أو مرّر من الحافة للاختبار",
  "formUnchanged": "النموذج نظيف — الرجوع يمر بحرية",
  "formChanged": "النموذج مُعدَّل — الرجوع محظور",
  "editToMakeDirty": "عدّل الحقل أدناه لتلطيخ النموذج",
  "testHapticsDemoTitle": "الاهتزازات التفاعلية",
  "testHapticsSubtitle": "ردود فعل لمسية · مدمجة تلقائياً",
  "hapticTypes": "شدة الاهتزاز",
  "hapticLight": "خفيف",
  "hapticMedium": "متوسط",
  "hapticHeavy": "قوي",
  "hapticSelection": "اختيار",
  "hapticLightHint": "ضغط زر، تفاعل خفيف",
  "hapticMediumHint": "تأكيد، إجراء ناجح",
  "hapticHeavyHint": "خطأ، إجراء مدمر",
  "hapticSelectionHint": "تمرير، picker، تبديل",
  "feedbackIntegration": "تلقائي عبر context.feedback.*",
  "tapToFeel": "اضغط للإحساس",
  "hapticEnabled": "الاهتزازات مُفعَّلة",
  "hapticDisabled": "الاهتزازات مُعطَّلة (AppFeatures.haptics = false)",
  "active": "نشط",
  "inactive": "غير نشط",
  "customSheet": "قائمة مخصصة",
  "filterSheet": "قائمة فلترة",
  "textInputs": "حقول الإدخال",
  "tabNavigation": "التبويبات",
  "skeletonTemplates": "قوالب Skeleton",
  "skeletonListTile": "عنصر قائمة",
  "skeletonCard": "بطاقة",
  "skeletonGridItem": "عنصر شبكة",
  "skeletonProfile": "ملف شخصي",
  "skeletonStatRow": "إحصائيات",
  "withLottie": "مع Lottie",
  "withIcon": "مع أيقونة",
  "lottieAnimations": "رسوم Lottie",
  "testLottieHint": "استبدل الأيقونات بملفات Lottie حقيقية من LottieFiles.com",
  "testFeatureWizardTitle": "معالج Feature",
  "testFeatureWizardSubtitle": "5 خطوات: entity → شاشة",
  "stepDomain": "1. طبقة Domain",
  "stepData": "2. طبقة البيانات",
  "stepUseCases": "3. Use Cases والحقن",
  "stepRoute": "4. الـ Route",
  "stepPresentation": "5. طبقة العرض",
  "copyCode": "نسخ",
  "codeCopied": "تم النسخ!",
  "prevStep": "السابق",
  "nextStep": "التالي",
  "testNavStackTitle": "معالج Navigation Stack",
  "testNavStackSubtitle": "دفع · استبدال · رجوع",
  "currentStack": "المكدس الحالي",
  "whenToUse": "متى تستخدم",
  "stackEmpty": "المكدس فارغ",
  "testPlatformServicesDemoTitle": "خدمات النظام",
  "testPlatformServicesSubtitle": "خدمات مُفعَّلة · أعلام AppFeatures",
  "serviceEnabled": "مُفعَّل",
  "serviceDisabled": "معطَّل",
  "enableHint": "للتفعيل: AppFeatures.{flag} = true",
  "testService": "اختبر",
  "optionalPlatformServices": "خدمات النظام الاختيارية",
  "platformPermissions": "صلاحيات النظام",
  "optionalModules": "وحدات اختيارية",
  "firebaseModules": "وحدات Firebase",
  "testFailureDemoTitle": "سيناريوهات الأخطاء",
  "testFailureDemoSubtitle": "جميع أنواع الأخطاء · UiAction",
  "simulatedResult": "نتيجة المحاكاة",
  "tapToSimulate": "اضغط على خطأ للمحاكاة",
  "uiActionShowError": "ShowError",
  "uiActionNavigateToLogin": "NavigateToLogin",
  "uiActionSilent": "Silent",
  "canRetry": "canRetry",
  "testConnectivityTitle": "الاتصال ودورة الحياة",
  "testConnectivitySubtitle": "مراقب الشبكة · دورة حياة التطبيق",
  "networkState": "حالة الشبكة",
  "appLifecycle": "دورة حياة التطبيق",
  "usagePattern": "نمط الاستخدام",
  "testSyncQueueTitle": "مراقب طابور المزامنة",
  "testSyncQueueSubtitle": "أوفلاين أولاً · طابور · معالجة تلقائية",
  "pendingQueue": "الطابور المعلّق",
  "clearQueue": "مسح الطابور",
  "simulatedOnline": "محاكاة: متصل — الطابور يُعالَج تلقائياً",
  "simulatedOffline": "محاكاة: غير متصل — العمليات تُخزَّن محلياً",
  "addedAgo": "أُضيفت {time}",
  "flowVisualizer": "مسار الخطأ",
  "tapFailureHint": "اضغط على خطأ لتتبّع مساره عبر الطبقات",
  "testBlocStatesDemoTitle": "آلة حالات BLoC",
  "testBlocStatesSubtitle": "Freezed · BlocConsumer · انتقالات",
  "triggerLoad": "تحميل البيانات",
  "injectError": "حقن خطأ",
  "stateHistory": "سجل الحالات",
  "stateDefinition": "تعريف الحالة",
  "testApiSimulatorTitle": "محاكي طلبات API",
  "testApiSimulatorSubtitle": "الطبقات · التوقيت · Pipeline",
  "sendRequest": "إرسال الطلب",
  "requestSuccess": "نجح الطلب",
  "requestFailed": "فشل الطلب",
  "networkDelay": "تأخير الشبكة",
  "injectFailure": "حقن فشل",
  "injectNone": "بدون (نجاح)",
  "requestConfig": "إعدادات الطلب",
  "pipelineTitle": "خط المعالجة",
  "pressSendHint": "اضغط «إرسال الطلب» لمحاكاة استدعاء API كامل",
  "activeDevicesTitle": "الأجهزة المرتبطة",
  "activeDevicesCount": "الأجهزة النشطة: {count} من {max}",
  "revokeAllDevices": "تسجيل خروج من كل الأجهزة",
  "revokeAllDevicesMessage": "سيتم تسجيل الخروج من جميع الأجهزة ما عدا هذا الجهاز.",
  "primaryDeviceBadge": "الأساسي",
  "thisDeviceActiveNow": "هذا الجهاز  •  نشط الآن",
  "lastActive": "آخر نشاط: {date}",
  "revokeDeviceTitle": "تسجيل خروج الجهاز",
  "revokeDeviceMessage": "هل تريد تسجيل الخروج من \"{device}\"؟",
  "today": "اليوم",
  "yesterday": "أمس",
  "daysAgo": "منذ {days} أيام",
  "syncQueue": "طابور المزامنة",
  "failedQueue": "طابور الأخطاء",
  "failedToSync": "فشل في المزامنة",
  "completed": "مكتمل",
  "clearCompleted": "مسح المكتمل",
  "cancelled": "ملغي",
  "attempts": "محاولات",
  "product": "منتج",
  "clearedCompleted": "تم مسح العناصر المكتملة",
  "noFailedItems": "لا توجد عناصر فاشلة لإعادة المحاولة",
  "retryingFailed": "جاري إعادة محاولة العناصر الفاشلة",
  "noCompletedItems": "لا توجد عناصر مكتملة للمسح",
  "clearedQueue": "تم مسح الطابور",
  "clearAll": "مسح الكل",
  "products": "منتجات",
  "lastSeenAgo": {
    "now": "آخر ظهور منذ لحظات",
    "minutes": "آخر ظهور منذ {minutes} دقيقة",
    "hours": "آخر ظهور منذ {hours} ساعة",
    "yesterday": "آخر ظهور أمس",
    "days": "آخر ظهور منذ {days} أيام",
    "week": "آخر ظهور منذ أسبوع",
    "weeks": "آخر ظهور منذ {weeks} أسابيع",
    "month": "آخر ظهور منذ شهر",
    "months": "آخر ظهور منذ {months} أشهر",
    "longTime": "آخر ظهور منذ زمن طويل"
  }
};
static const Map<String,dynamic> _en = {
  "password": "Password",
  "phone": "Phone Number",
  "login": "Login",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "done": "Done",
  "loading": "Loading",
  "dismiss": "Dismiss",
  "success": "Success",
  "info": "Info",
  "error": "Error",
  "warning": "Warning",
  "about": "About",
  "option": "Option",
  "somethingWrong": "Something went wrong! Please try again",
  "unknownError": "Something went wrong. Please try again.",
  "noInternetConnection": "No internet connection, try again later",
  "noItems": "No items",
  "badRequest": "Bad request",
  "unauthorised": "Unauthorised",
  "notFound": "Not found",
  "invalidInput": "Invalid input",
  "serverError": "Server error",
  "cacheError": "Cache error",
  "parseDataError": "Response data error, please try again",
  "permissionDenied": "Permission denied, please allow access",
  "permissionPermanentlyDenied": "Permission permanently denied, open App Settings to enable it",
  "sessionTimedOut": "Session timed out",
  "sessionRevoked": "You have been signed out from another device",
  "notPrimaryDevice": "Only the primary device can sign out other devices",
  "deviceNotFound": "Device not found or already removed",
  "invalidPassword": "Password required",
  "invalidPasswordLength": "The password must be at least 8 characters and at most 30 characters",
  "passwordValidationError": "The password must contain at least one number and at least one letter",
  "invalidEmailAddress": "Invalid email address",
  "welcomeBack": "Welcome back",
  "loginToYourAccount": "Log in to your account",
  "eMail": "E-mail",
  "typeEmail": "Type your email",
  "forgotPassword": "Forgot Password?",
  "dontHaveAccount": "Don't have an account?",
  "continueGuest": "Continue as Guest",
  "SignUp": "Sign up",
  "justNow": "Just now",
  "minAgo": "Min ago",
  "hAgo": "H ago",
  "dAgo": "Day ago",
  "wAgo": "W ago",
  "moAgo": "Mo ago",
  "yAgo": "Y ago",
  "appAppearance": "App appearance",
  "theme": "Theme",
  "widgetLibraryTitle": "Widget & Extensions Demo",
  "toast": "Toast",
  "toastMessage": "Toast message",
  "toastSuccess": "Toast Success",
  "toastError": "Toast Error",
  "snackbar": "SnackBar",
  "dialog": "Dialog",
  "dialogContent": "Dialog content",
  "title": "Title",
  "sheetContent": "Sheet content",
  "bottomSheet": "Bottom Sheet",
  "states": "States",
  "emptyState": "Empty state",
  "errorRetry": "Error + Retry",
  "noInternet": "No internet",
  "placeholders": "Placeholders",
  "feedback": "Feedback",
  "images": "Images",
  "layout": "Layout",
  "misc": "Misc",
  "indicators": "Indicators",
  "dateMaterial": "Date (Material)",
  "dateCalendar": "Date (Calendar)",
  "timeMaterial": "Time (Material)",
  "retry": "Retry",
  "updateAvailableTitle": "Update available",
  "updateAvailableMessage": "A new version of the app is available. Updating is recommended.",
  "updateNow": "Update",
  "later": "Later",
  "reconnecting": "Reconnecting...",
  "syncing": "Syncing...",
  "syncPattern": "Sync Pattern",
  "goOffline": "Go offline",
  "goOnline": "Go online",
  "syncQueueEmpty": "Sync Queue Empty",
  "localStorage": "Local Storage",
  "serverState": "Server State",
  "productStock": "Stock",
  "connectionOnline": "Online - auto-sync is active",
  "connectionOffline": "Offline - saved locally",
  "tapToDisconnect": "Tap to disconnect",
  "tapToReconnect": "Tap to reconnect",
  "syncStatusPending": "Pending",
  "syncStatusProcessing": "Uploading",
  "syncStatusSynced": "Synced",
  "syncStatusFailed": "Failed",
  "syncStatusOffline": "Offline",
  "queueSectionTitle": "Sync Queue",
  "eventLogTitle": "Event Log",
  "settings": "Settings",
  "appearance": "Appearance",
  "language": "Language",
  "notifications": "Notifications",
  "enableNotifications": "Enable Notifications",
  "appInfo": "About",
  "appVersion": "App Version",
  "clearCache": "Clear Cache",
  "cacheClearedSuccessfully": "Cache cleared successfully",
  "themeLight": "Light",
  "themeDark": "Dark",
  "themeSystem": "System default",
  "typography": "Typography",
  "discardChangesTitle": "Discard changes?",
  "discardChangesMessage": "You have unsaved changes. Are you sure you want to leave?",
  "profile": "Profile",
  "editProfile": "Edit Profile",
  "birthdate": "Date of Birth",
  "address": "Address",
  "send": "Send",
  "backToLogin": "Back to Login",
  "forgotPasswordHint": "Enter your email and we'll send you a password reset link",
  "checkYourEmail": "Check your email",
  "resetLinkSentTo": "Reset link sent to",
  "firstName": "First Name",
  "lastName": "Last Name",
  "confirmPassword": "Confirm Password",
  "passwordMismatch": "Passwords do not match",
  "save": "Save",
  "add": "Add",
  "delete": "Delete",
  "apply": "Apply",
  "reset": "Reset",
  "filter": "Filter",
  "sortBy": "Sort by",
  "deleteConfirmTitle": "Confirm Delete",
  "deleteConfirmMessage": "Are you sure you want to delete this item?",
  "addedSuccessfully": "Added successfully",
  "updatedSuccessfully": "Updated successfully",
  "deletedSuccessfully": "Deleted successfully",
  "fieldRequired": "This field is required",
  "invalidEmail": "Invalid email address",
  "passwordLength": "Password must be between 8 and 30 characters",
  "passwordWeak": "Weak password",
  "invalidPhone": "Invalid phone number",
  "logOut": "Log Out",
  "logoutConfirmTitle": "Log Out?",
  "logoutConfirmMessage": "Are you sure you want to log out?",
  "exitAppTitle": "Exit App?",
  "exitAppMessage": "Are you sure you want to exit the application?",
  "tabHome": "Home",
  "tabProfile": "Profile",
  "tabSettings": "Settings",
  "homeSubtitle": "Explore what the app can do",
  "quickAccess": "Quick Access",
  "widgetCatalogTitle": "Widget Catalog",
  "widgetCatalogSubtitle": "Browse all available UI components",
  "users": "Users",
  "usersSubtitle": "Browse the user list",
  "testDashboard": "Template Showcase",
  "testFormsDemoTitle": "Forms Demo",
  "testFormsSubtitle": "Validation · Controllers · Submit",
  "testStatesDemoTitle": "States Demo",
  "testStatesSubtitle": "Loading · Error · Empty · NoInternet",
  "testThemeDemoTitle": "Colors & Typography",
  "testThemeSubtitle": "Color palette & text scale",
  "fullName": "Full Name",
  "submitSuccess": "Submitted successfully",
  "selectState": "Select State",
  "colorPalette": "Color Palette",
  "maintenance": "Under Maintenance",
  "testSettingsDemoTitle": "App Settings",
  "testSettingsSubtitle": "Language · Theme · Typography",
  "feedbackStyle": "Feedback Style",
  "testFormValidationTitle": "Form Validation",
  "testFormValidationSubtitle": "States · Guards · Visual Feedback",
  "autoValidate": "Auto Validate",
  "submitGuard": "Submit Guard",
  "formStateLabel": "Form State",
  "formValid": "Valid",
  "formInvalid": "Invalid",
  "simulateApiError": "Simulate API Error",
  "doubleSubmitBlocked": "Double Submit Blocked!",
  "beforeFirstSubmit": "Before First Submit",
  "testPaginationDemoTitle": "Pagination Demo",
  "testPaginationSubtitle": "Loading Styles · Display Modes",
  "loadingStyle": "Loading Style",
  "displayMode": "Display Mode",
  "pageSize": "Page Size",
  "delayMs": "Delay",
  "errorChance": "Error Chance",
  "shimmerList": "Shimmer List",
  "shimmerGrid": "Shimmer Grid",
  "skeletonRows": "Skeleton",
  "spinnerStyle": "Spinner",
  "viewList": "List",
  "viewGrid2": "Grid ×2",
  "viewGrid3": "Grid ×3",
  "simulateError": "Simulate Error",
  "simulateEmpty": "Simulate Empty",
  "page": "Page",
  "items": "Items",
  "pageLoadingStyle": "Page Loading Indicator",
  "loadingMore": "Loading more…",
  "testCrudDemoTitle": "CRUD Simulation",
  "testCrudSubtitle": "Add · Edit · Delete · Rollback",
  "addProduct": "Add Product",
  "editProduct": "Edit Product",
  "productName": "Product Name",
  "productPrice": "Price",
  "productCategory": "Category",
  "simulateServerError": "Simulate Server Error",
  "optimisticUpdates": "Optimistic Updates",
  "eventLog": "Event Log",
  "clearLog": "Clear Log",
  "rollbackApplied": "Rolled Back!",
  "noEventsYet": "No events yet",
  "testPredictiveBackTitle": "Predictive Back",
  "testPredictiveBackSubtitle": "PopScope · Back Guard · Android 14+",
  "manifestEnabled": "AndroidManifest configured",
  "backFree": "Free Back",
  "backFreeDesc": "canPop: true — system handles back, predictive preview on Android 14+",
  "backConfirm": "Confirm on Back",
  "backConfirmDesc": "canPop: false — intercepts back and shows a confirmation dialog",
  "backDirtyGuard": "Dirty Form Guard",
  "backDirtyGuardDesc": "canPop: false — blocks back only when the form has unsaved changes",
  "pressBackToTest": "Press back or swipe from edge to test",
  "formUnchanged": "Form is clean — back passes through",
  "formChanged": "Form is dirty — back is blocked",
  "editToMakeDirty": "Edit the field below to make the form dirty",
  "testHapticsDemoTitle": "Haptic Feedback",
  "testHapticsSubtitle": "Touch Feedback · Auto-integrated",
  "hapticTypes": "Haptic Intensities",
  "hapticLight": "Light",
  "hapticMedium": "Medium",
  "hapticHeavy": "Heavy",
  "hapticSelection": "Selection",
  "hapticLightHint": "Button press, passive tap",
  "hapticMediumHint": "Confirm, success action",
  "hapticHeavyHint": "Error, destructive action",
  "hapticSelectionHint": "Scroll snap, picker change",
  "feedbackIntegration": "Auto via context.feedback.*",
  "tapToFeel": "Tap to feel",
  "hapticEnabled": "Haptics Enabled",
  "hapticDisabled": "Haptics Disabled (AppFeatures.haptics = false)",
  "active": "Active",
  "inactive": "Inactive",
  "customSheet": "Custom Sheet",
  "filterSheet": "Filter Sheet",
  "textInputs": "Text Inputs",
  "tabNavigation": "Tab Navigation",
  "skeletonTemplates": "Skeleton Templates",
  "skeletonListTile": "List Tile",
  "skeletonCard": "Card",
  "skeletonGridItem": "Grid Item",
  "skeletonProfile": "Profile",
  "skeletonStatRow": "Stats Row",
  "withLottie": "With Lottie",
  "withIcon": "With Icon",
  "lottieAnimations": "Lottie Animations",
  "testLottieHint": "Replace icons with real Lottie files from LottieFiles.com",
  "testFeatureWizardTitle": "Feature Wizard",
  "testFeatureWizardSubtitle": "5-step: entity → screen",
  "stepDomain": "1. Domain Layer",
  "stepData": "2. Data Layer",
  "stepUseCases": "3. Use Cases & DI",
  "stepRoute": "4. Route",
  "stepPresentation": "5. Presentation Layer",
  "copyCode": "Copy",
  "codeCopied": "Copied!",
  "prevStep": "Back",
  "nextStep": "Next",
  "testNavStackTitle": "Navigation Stack",
  "testNavStackSubtitle": "push · replace · pop",
  "currentStack": "Current Stack",
  "whenToUse": "When to Use",
  "stackEmpty": "Stack is empty",
  "testPlatformServicesDemoTitle": "Platform Services",
  "testPlatformServicesSubtitle": "AppFeatures flags · Enabled services",
  "serviceEnabled": "Enabled",
  "serviceDisabled": "Disabled",
  "enableHint": "To enable: AppFeatures.{flag} = true",
  "testService": "Test",
  "optionalPlatformServices": "Optional Platform Services",
  "platformPermissions": "Platform Permissions",
  "optionalModules": "Optional Modules",
  "firebaseModules": "Firebase Modules",
  "testFailureDemoTitle": "Failure Scenarios",
  "testFailureDemoSubtitle": "FailureUiMapper · All failure types",
  "simulatedResult": "Simulated Result",
  "tapToSimulate": "Tap a failure to simulate",
  "uiActionShowError": "ShowError",
  "uiActionNavigateToLogin": "NavigateToLogin",
  "uiActionSilent": "Silent",
  "canRetry": "canRetry",
  "testConnectivityTitle": "Connectivity & Lifecycle",
  "testConnectivitySubtitle": "NetworkStateMonitor · AppLifecycleService",
  "networkState": "Network State",
  "appLifecycle": "App Lifecycle",
  "usagePattern": "Usage Pattern",
  "testSyncQueueTitle": "Sync Queue Monitor",
  "testSyncQueueSubtitle": "Offline-first · Queue · Auto-drain",
  "pendingQueue": "Pending Queue",
  "clearQueue": "Clear Queue",
  "simulatedOnline": "Simulated: Online — queue drains automatically",
  "simulatedOffline": "Simulated: Offline — operations queued locally",
  "addedAgo": "Added {time}",
  "flowVisualizer": "Error Flow",
  "tapFailureHint": "Tap a failure to trace its flow through the layers",
  "testBlocStatesDemoTitle": "BLoC State Machine",
  "testBlocStatesSubtitle": "Freezed · BlocConsumer · Transitions",
  "triggerLoad": "Load Data",
  "injectError": "Inject Error",
  "stateHistory": "State History",
  "stateDefinition": "State Definition",
  "testApiSimulatorTitle": "API Request Simulator",
  "testApiSimulatorSubtitle": "Pipeline · Layers · Timing",
  "sendRequest": "Send Request",
  "requestSuccess": "Request Succeeded",
  "requestFailed": "Request Failed",
  "networkDelay": "Network Delay",
  "injectFailure": "Inject Failure",
  "injectNone": "None (Success)",
  "requestConfig": "Request Config",
  "pipelineTitle": "Pipeline",
  "pressSendHint": "Press 'Send Request' to simulate a full API call",
  "activeDevicesTitle": "Linked Devices",
  "activeDevicesCount": "Active devices: {count} of {max}",
  "revokeAllDevices": "Log out all devices",
  "revokeAllDevicesMessage": "All devices except this one will be logged out.",
  "primaryDeviceBadge": "Primary",
  "thisDeviceActiveNow": "This device  •  Active now",
  "lastActive": "Last active: {date}",
  "revokeDeviceTitle": "Log out device",
  "revokeDeviceMessage": "Log out from \"{device}\"?",
  "today": "Today",
  "yesterday": "Yesterday",
  "daysAgo": "{days} days ago",
  "syncQueue": "Sync Queue",
  "failedQueue": "Failed Queue",
  "failedToSync": "Failed to sync",
  "completed": "Completed",
  "clearCompleted": "Clear Completed",
  "cancelled": "Cancelled",
  "attempts": "Attempts",
  "product": "Product",
  "clearedCompleted": "Cleared completed items",
  "noFailedItems": "No failed items to retry",
  "retryingFailed": "Retrying failed items",
  "noCompletedItems": "No completed items to clear",
  "clearedQueue": "Queue cleared",
  "clearAll": "Clear All",
  "products": "Products",
  "lastSeenAgo": {
    "now": "last seen just now",
    "minutes": "last seen {minutes} minutes ago",
    "hours": "last seen {hours} hours ago",
    "yesterday": "last seen yesterday",
    "days": "last seen {days} days ago",
    "week": "last seen a week ago",
    "weeks": "last seen {weeks} weeks ago",
    "month": "last seen a month ago",
    "months": "last seen {months} months ago",
    "longTime": "last seen a long time ago"
  }
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
