// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "SignUp": "التسجيل",
  "accessControlDisabled": "الصلاحيات معطَّلة في هذه النسخة",
  "accessNotEnforced": "الخادم لا يطبّق الصلاحيات بعد — المنح يُحفَظ لكن لا يُرفَض شيء",
  "accountStatus": "حالة الحساب",
  "active": "نشط",
  "activeDevicesCount": "الأجهزة النشطة: {count} من {max}",
  "activeDevicesSubtitle": "الأماكن التي سجّلت الدخول منها إلى حسابك الآن",
  "activeDevicesTitle": "الأجهزة المرتبطة",
  "addedAgo": "أُضيفت {time}",
  "alreadyHaveAccount": "لديك حساب بالفعل؟",
  "appAppearance": "مظهر التطبيق",
  "appInfo": "حول التطبيق",
  "appVersion": "إصدار التطبيق",
  "appearance": "المظهر",
  "apply": "تطبيق",
  "attachmentAdd": "إضافة صورة",
  "attachmentCaptureFailed": "تعذّر حفظ الصورة — يرجى التقاطها مجدداً",
  "attachmentDownloadFailed": "تعذّر تنزيل الملف — أعد المحاولة",
  "attachmentFailed": "تعذّر التحميل — اضغط للمحاولة",
  "attachmentLoading": "جارٍ التحميل…",
  "attachmentMissingLocally": "لم يعد هذا الملف على الجهاز — أعد إرفاقه",
  "attachmentNotOnServer": "لم يعد هذا الملف متوفراً",
  "attachmentOfflineUnavailable": "غير متوفّر دون اتصال",
  "attachmentOpenFailed": "لا يوجد تطبيق على هذا الجهاز يفتح هذا الملف",
  "attachmentServerOnly": "الملف غير محمّل على هذا الجهاز — اضغط لتنزيله",
  "attachmentUnavailable": "اضغط لإعادة التحميل",
  "attachments": "المرفقات",
  "attachmentsEmpty": "لا مرفقات بعد",
  "backToLogin": "العودة إلى تسجيل الدخول",
  "badRequest": "طلب غير صالح",
  "cacheClearedSuccessfully": "تم مسح الذاكرة المؤقتة",
  "cacheError": "خطأ في الذاكرة المؤقتة",
  "cancel": "إلغاء",
  "cancelled": "مُلغى",
  "changePassword": "تغيير كلمة المرور",
  "checkYourEmail": "تحقق من بريدك الإلكتروني",
  "chooseFormat": "اختر الصيغة",
  "clearCache": "مسح الذاكرة المؤقتة",
  "clearCompleted": "مسح العناصر المكتملة",
  "clearFilters": "مسح التصفية",
  "clearedCompleted": "تم مسح العناصر المكتملة",
  "completed": "مكتمل",
  "confirm": "تأكيد",
  "confirmPassword": "تأكيد كلمة المرور",
  "continueGuest": "استمرّ كضيف",
  "createAccount": "أنشئ حساباً",
  "currentPassword": "كلمة المرور الحالية",
  "dAgo": "يوم مضى",
  "dataTransfer": "الاستيراد والتصدير",
  "dataTransferSubtitle": "نزِّل بياناتك، أو استوردها من ملف",
  "daysAgo": "منذ {days} أيام",
  "delete": "حذف",
  "deleteConfirmMessage": "هل أنت متأكد من حذف هذا العنصر؟",
  "deleteConfirmTitle": "تأكيد الحذف",
  "deviceEmpty": "لا توجد جلسات فعّالة",
  "deviceExpiresAt": "تنتهي",
  "deviceLastActive": "آخر نشاط",
  "deviceNoOthers": "لا توجد أجهزة أخرى",
  "deviceNotFound": "الجهاز غير موجود أو أُلغي مسبقاً",
  "deviceRevoke": "إنهاء الجلسة",
  "deviceRevokeConfirmMessage": "سيُطلب من هذا الجهاز تسجيل الدخول من جديد. لن يتأثر أي جهاز آخر.",
  "deviceRevokeConfirmTitle": "إنهاء هذه الجلسة؟",
  "deviceRevokeDone": "أُنهيت الجلسة",
  "deviceRevokeOthers": "إنهاء الجلسات الأخرى",
  "deviceRevokeOthersConfirmMessage": "سيُطلب من كل الأجهزة الأخرى تسجيل الدخول من جديد. جهازك الحالي يبقى كما هو.",
  "deviceRevokeOthersConfirmTitle": "إنهاء الجلسات الأخرى؟",
  "deviceRevokeOthersDone": "أُنهيت {} جلسة",
  "deviceSecurityNote": "لا ترى جهازاً تعرفه؟ أنهِ جلسته وغيّر كلمة مرورك.",
  "deviceSignedInAt": "سُجّل الدخول",
  "deviceThisDevice": "هذا الجهاز",
  "deviceUnknown": "جهاز غير معروف",
  "dismiss": "تجاهل",
  "done": "تم",
  "dontHaveAccount": "ليس لديك حساب؟",
  "eMail": "البريد الإلكتروني",
  "edit": "تعديل",
  "editProfile": "تعديل الملف الشخصي",
  "emailVerifiedNo": "البريد غير مؤكَّد",
  "emailVerifiedYes": "البريد مؤكَّد",
  "enableNotifications": "تفعيل الإشعارات",
  "endOfList": "نهاية القائمة",
  "error": "خطأ",
  "eventLogTitle": "سجل الأحداث",
  "exitAppMessage": "هل أنت متأكد من الخروج من التطبيق؟",
  "exitAppTitle": "الخروج من التطبيق؟",
  "exportAgain": "تصدير مرة أخرى",
  "exportClearAll": "مسح",
  "exportColumns": "الأعمدة",
  "exportFilters": "التصفية",
  "exportFiltersHint": "اتركه فارغاً لتصدير كل شيء",
  "exportFormat": "الصيغة",
  "exportOpen": "فتح",
  "exportPreparing": "يجري تجهيز الملف…",
  "exportReadyTitle": "ملفك جاهز",
  "exportRowLimit": "حتى {} صف في كل تصدير",
  "exportRun": "تصدير",
  "exportSelectAll": "تحديد الكل",
  "exportShare": "مشاركة",
  "exportTitle": "تصدير",
  "feedbackStyle": "نمط التغذية الراجعة",
  "fieldRequired": "هذا الحقل مطلوب",
  "fileOpenExternal": "فتح في تطبيق آخر",
  "fileOpenFailed": "لا يوجد تطبيق على هذا الجهاز يفتح هذا الملف",
  "filePreview": "معاينة",
  "filePreviewEmpty": "هذا الملف فارغ",
  "filePreviewExternal": "معاينة في تطبيق آخر",
  "filePreviewFailed": "تعذّرت قراءة هذا الملف",
  "filePreviewHeaderOnly": "رؤوس الأعمدة فقط — بلا صفوف بيانات",
  "filePreviewRows": "{} صف",
  "filePreviewTruncated": "أول {} صف",
  "fileReady": "الملف جاهز",
  "fileSave": "حفظ في الجهاز",
  "fileSaveFailed": "تعذّر حفظ الملف",
  "fileSaveHint": "اختر مكان الحفظ",
  "fileSaved": "حُفظ",
  "fileShare": "مشاركة",
  "filter": "تصفية",
  "forbiddenAction": "لا تملك صلاحية تنفيذ هذا الإجراء",
  "forgotPassword": "هل نسيت كلمة المرور؟",
  "forgotPasswordHint": "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة تعيين كلمة المرور",
  "formValid": "صالح",
  "formatCsvHint": "يفتح بأي برنامج · سهل التعديل كنص",
  "formatXlsxHint": "يحفظ التواريخ والأرقام بأنواعها · الأنسب لـExcel",
  "fullNameOptional": "الاسم الكامل (اختياري)",
  "hAgo": "ساعة مضت",
  "homeSubtitle": "استكشف إمكانيات التطبيق",
  "importColumnExample": "مثال: {}",
  "importColumnsHint": "هذه وحدها ما يحتاجه الملف. وأي عمود آخر يُتجاهَل.",
  "importColumnsTitle": "الأعمدة التي تملؤها",
  "importCommitting": "يجري الاستيراد…",
  "importConfirm": "استيراد {} صف",
  "importDeleteRow": "حذف السطر",
  "importDoneTitle": "انتهى الاستيراد",
  "importDownloadTemplate": "تنزيل القالب",
  "importDuplicateOf": "مكرر مع السطر {}",
  "importEditedNotice": "عدّلت صفوفاً — أعد الفحص قبل الاستيراد",
  "importErrorsTruncated": "تُعرض أول {} مشكلة",
  "importFailedRows": "فشل {}",
  "importGridTab": "البيانات",
  "importInserted": "أُضيف {}",
  "importListTab": "المشاكل",
  "importNoRowsShown": "لا صفوف لعرضها",
  "importNothingValid": "لا يصلح أي صف في هذا الملف للاستيراد",
  "importNothingWritten": "لم يُحفظ شيء بعد",
  "importOnlyProblems": "المشاكل فقط ({})",
  "importOptional": "اختياري",
  "importPickFile": "اختر ملفاً",
  "importRecheck": "إعادة الفحص",
  "importRequired": "إلزامي",
  "importReviewTitle": "راجِع قبل الاستيراد",
  "importRowLabel": "الصف {}",
  "importRowsInvalid": "{} صف فيه مشكلة",
  "importRowsTooMany": "الملف أكبر من أن يُعدَّل هنا. صحّحه بـExcel وارفعه من جديد.",
  "importRowsValid": "{} صف جاهز",
  "importShowingRows": "يُعرض {} من {} صف",
  "importSkipped": "تم تخطي {}",
  "importStartOver": "استيراد ملف آخر",
  "importSystemColumns": "تملؤها المنظومة: {}",
  "importTemplateReady": "نُزِّل القالب",
  "importTitle": "استيراد",
  "importUnsupported": "هذا العنصر غير قابل للاستيراد",
  "importUpdated": "حُدِّث {}",
  "importValidating": "يجري فحص الملف…",
  "importWarnings": "سيُتخطّى {} صف",
  "importWholeRow": "الصف كاملاً",
  "inactive": "غير نشط",
  "info": "معلومة",
  "invalidEmailAddress": "عنوان البريد الإلكتروني غير صالح",
  "invalidInput": "الإدخال غير صالح",
  "invalidPassword": "كلمة مرور مطلوبة",
  "invalidPasswordLength": "يجب ألا تقل كلمة المرور عن ٨ أحرف ولا تزيد عن ٣٠ حرفاً",
  "invalidPhone": "رقم الهاتف غير صحيح",
  "justNow": "الآن",
  "language": "اللغة",
  "lastActive": "آخر نشاط: {date}",
  "lastName": "اسم العائلة",
  "lastSeenAgo": {
    "now": "آخر ظهور منذ لحظات",
    "minutes": "آخر ظهور منذ {minutes} دقيقة",
    "hours": "آخر ظهور منذ {hours} ساعة",
    "yesterday": "آخر ظهور أمس",
    "days": "آخر ظهور منذ {days} أيام",
    "week": "آخر ظهور منذ أسبوع",
    "weeks": "آخر ظهور منذ {weeks} أسابيع",
    "month": "آخر ظهور منذ شهر",
    "months": "آخر ظهور منذ {months} أشهر",
    "longTime": "آخر ظهور منذ زمن طويل"
  },
  "later": "لاحقاً",
  "loadMore": "عرض المزيد",
  "loadMoreFailed": "تعذّر تحميل المزيد",
  "loading": "جارٍ التحميل",
  "loadingMore": "جارٍ تحميل المزيد…",
  "logOut": "تسجيل الخروج",
  "login": "تسجيل الدخول",
  "loginDisabled": "حسابك معطَّل",
  "loginPendingApproval": "حسابك قيد مراجعة الإدارة",
  "loginRejected": "طلب تسجيلك مرفوض",
  "loginSuspended": "حسابك موقوف مؤقتاً",
  "loginToYourAccount": "تسجيل الدخول إلى حسابك",
  "logoutConfirmMessage": "هل أنت متأكد من تسجيل الخروج؟",
  "logoutConfirmTitle": "تسجيل الخروج؟",
  "logoutPendingWorkMessage": "{count} تغيير لم يصل الخادم بعد. تسجيل الخروج يتركها على هذا الجهاز، ولا يستطيع إرسالها إلا هذا الحساب. هل تريد الخروج رغم ذلك؟",
  "logoutPendingWorkTitle": "تغييرات لم تُرسَل بعد",
  "lottieAnimations": "رسوم Lottie",
  "maintenance": "قيد الصيانة",
  "memberSince": "عضو منذ",
  "minAgo": "دقيقة مضت",
  "moAgo": "شهر مضى",
  "networkChecking": "جارٍ التحقق من الاتصال",
  "networkConnected": "متصل بالشبكة",
  "newPassword": "كلمة المرور الجديدة",
  "noCompletedItems": "لا توجد عناصر مكتملة للمسح",
  "noDataFound": "لا توجد بيانات",
  "noInternet": "لا إنترنت",
  "noInternetConnection": "لا يوجد اتصال بالإنترنت، حاول مرة أخرى لاحقاً",
  "notFound": "غير موجود",
  "notPrimaryDevice": "لا تملك صلاحية تسجيل خروج الأجهزة الأخرى",
  "notSpecified": "غير محدَّد",
  "notificationCenterClearAll": "حذف الكل",
  "notificationCenterClearConfirmMessage": "سيُحذف كل ما بالقائمة، ولا يمكن التراجع.",
  "notificationCenterClearConfirmTitle": "حذف كل الإشعارات؟",
  "notificationCenterEmpty": "لا توجد إشعارات بعد",
  "notificationCenterMarkAllRead": "تعليم الكل كمقروء",
  "notificationCenterTitle": "مركز الإشعارات",
  "notificationCenterUntitled": "إشعار",
  "notifications": "الإشعارات",
  "offlineListHint": "تعذّر الوصول إلى الخادم — تحقّق من الاتصال ثم أعد المحاولة",
  "optimisticUpdates": "تحديثات تفاؤلية",
  "option": "اختياري",
  "overrideAllow": "سماح",
  "overrideDeny": "حظر",
  "overrideInherit": "وراثة",
  "parseDataError": "حدث خطأ في بيانات الاستجابة، يرجى المحاولة مرة أخرى",
  "password": "كلمة المرور",
  "passwordChangedSuccess": "تم تغيير كلمة المرور",
  "passwordMismatch": "كلمتا المرور غير متطابقتين",
  "passwordMustDiffer": "يجب أن تختلف كلمة المرور الجديدة عن الحالية",
  "passwordValidationError": "يجب أن تحتوي كلمة المرور على رقم واحد وحرف واحد على الأقل",
  "passwordWeak": "كلمة المرور ضعيفة",
  "passwordsDoNotMatch": "كلمتا المرور غير متطابقتين",
  "permissionClearAll": "لا شيء",
  "permissionDenied": "تم رفض الإذن المطلوب، يرجى منح صلاحية الوصول",
  "permissionImplies": "يمنح أيضاً: {}",
  "permissionLabelInferred": "التسمية مستنتَجة من اسم الإجراء",
  "permissionManageHint": "كل ما في هذا المورد، بما يُضاف إليه لاحقاً",
  "permissionPermanentlyDenied": "الإذن مرفوض نهائياً، افتح إعدادات التطبيق لتفعيله",
  "permissionSelectAll": "الكل",
  "permissionStale": "لم يعد معلَناً",
  "phone": "رقم الهاتف",
  "primaryDeviceBadge": "الأساسي",
  "profile": "الملف الشخصي",
  "queueSectionTitle": "طابور المزامنة",
  "quickAccess": "وصول سريع",
  "reconnecting": "جارٍ إعادة الاتصال…",
  "registerCta": "إنشاء الحساب",
  "registerSubtitle": "لا يستغرق دقيقة",
  "registerSuccess": "أُنشئ الحساب — أكّد بريدك للمتابعة",
  "registerTitle": "إنشاء حساب",
  "reset": "إعادة تعيين",
  "resetCode": "رمز الاستعادة",
  "resetCodeSentTo": "إن كان {email} مسجَّلاً لدينا فقد أرسلنا إليه رمزاً",
  "resetLinkSentTo": "تم إرسال رابط إعادة التعيين إلى",
  "resetPassword": "إعادة تعيين كلمة المرور",
  "retry": "إعادة المحاولة",
  "retryAfterFewMinutes": "أعد المحاولة بعد بضع دقائق.",
  "retryAfterLater": "أعد المحاولة لاحقاً.",
  "retryAfterUnderMinute": "أعد المحاولة بعد أقل من دقيقة.",
  "revokeAllDevices": "تسجيل الخروج من جميع الأجهزة",
  "revokeAllDevicesMessage": "سيتم تسجيل الخروج من جميع الأجهزة ما عدا هذا الجهاز.",
  "revokeDeviceMessage": "هل تريد تسجيل الخروج من «{device}»؟",
  "revokeDeviceTitle": "تسجيل الخروج من الجهاز",
  "roleActivate": "إعادة تفعيل",
  "roleCreate": "دور جديد",
  "roleDeactivate": "تعطيل",
  "roleEditorReadOnly": "الأدوار النظامية غير قابلة للتعديل — النظام يعتمد عليها",
  "roleEditorTitle": "الصلاحيات",
  "roleInactiveBadge": "معطَّل",
  "roleKeyHint": "حروف صغيرة وشرطة سفلية — يُستخدَم في النصوص البرمجية ولا يُعاد تسميته",
  "roleKeyLabel": "المعرّف",
  "roleMembers": "{} مستخدم",
  "roleNameArLabel": "الاسم بالعربية",
  "roleNameEnLabel": "الاسم بالإنجليزية",
  "rolePermissionsCount": "{} صلاحية",
  "roleSaved": "تم تحديث الصلاحيات",
  "roleStaleGrants": "{} صلاحية لم يعد الخادم يعلنها",
  "roleSystemBadge": "دور نظامي",
  "rolesEmpty": "لا توجد أدوار بعد",
  "rolesManageSubtitle": "إدارة الأدوار ومن يملك كل صلاحية",
  "rolesTitle": "الأدوار والصلاحيات",
  "rollbackApplied": "تم التراجع",
  "save": "حفظ",
  "screenComingSoon": "قيد الإنشاء",
  "screenComingSoonHint": "هذه الشاشة قيد الإنشاء وستتوفّر قريباً.",
  "security": "الأمان",
  "sendResetCode": "إرسال رمز الاستعادة",
  "serverError": "خطأ في الخادم",
  "serverUnreachable": "تعذّر الوصول إلى الخادم. اتصالك بالشبكة يعمل، غير أنّ الخادم لا يستجيب حالياً.",
  "serviceUnavailable": "الخدمة غير متاحة مؤقتاً بسبب ضغط أو صيانة.",
  "sessionExpiredMessage": "انتهت جلستك، سجّل الدخول من جديد",
  "sessionGuardBiometricReason": "أثبت هويتك لفتح التطبيق",
  "sessionGuardConfirmPinTitle": "أكِّد رقم القفل",
  "sessionGuardEnterPin": "أدخل رقم القفل لفتح التطبيق",
  "sessionGuardLockedTitle": "التطبيق مقفل",
  "sessionGuardPinMismatch": "الرقمان غير متطابقين، حاول مجدداً",
  "sessionGuardSetupPinSubtitle": "سيُطلب منك هذا الرقم لفتح التطبيق لاحقاً",
  "sessionGuardSetupPinTitle": "أنشئ رقم قفل",
  "sessionGuardUseBiometrics": "استخدم البصمة",
  "sessionGuardWrongPin": "رقمٌ غير صحيح، حاول مجدداً",
  "sessionRevoked": "دخل حسابَك جهازٌ آخر، فأُنهيت هذه الجلسة",
  "sessionTimedOut": "انتهت صلاحية الجلسة",
  "settings": "الإعدادات",
  "signIn": "تسجيل الدخول",
  "simulateServerError": "محاكاة خطأ الخادم",
  "simulatedOnline": "محاكاة: متصل — الطابور يُعالَج تلقائياً",
  "somethingWrong": "حدث خطأ ما، يرجى المحاولة مرة أخرى",
  "sortBy": "ترتيب حسب",
  "statusActive": "نشط",
  "statusDisabled": "معطَّل",
  "statusPendingVerification": "بانتظار تأكيد البريد",
  "success": "نجاح",
  "superAdminBadge": "صلاحية كاملة",
  "syncPattern": "نمط المزامنة",
  "syncQueue": "طابور المزامنة",
  "syncing": "جارٍ المزامنة…",
  "tabHome": "الرئيسية",
  "tabProfile": "الحساب",
  "tabSettings": "الإعدادات",
  "tapToFeel": "اضغط لتشعر",
  "tapToSimulate": "اضغط على خطأ للمحاكاة",
  "templateReady": "القالب جاهز",
  "testApiSimulatorSubtitle": "الطبقات · التوقيت · خط المعالجة",
  "testBlocStatesSubtitle": "Freezed · BlocConsumer · انتقالات",
  "testLottieHint": "استبدل الأيقونات بملفات Lottie حقيقية من LottieFiles.com",
  "themeDark": "داكن",
  "themeLight": "فاتح",
  "themeSystem": "تلقائي (حسب النظام)",
  "thisDeviceActiveNow": "هذا الجهاز  •  نشط الآن",
  "today": "اليوم",
  "tooManyRequests": "محاولات كثيرة خلال وقت قصير.",
  "transferDisabled": "الاستيراد والتصدير معطّل في هذه النسخة",
  "transferNoFormat": "لا توجد صيغة ملف مدعومة",
  "transferUnknownResource": "الخادم لا يوفّر هذا العنصر للنقل",
  "typeEmail": "اكتب بريدك الإلكتروني",
  "typeFullName": "بماذا نناديك؟",
  "typography": "الخطوط",
  "unauthorised": "غير مصرَّح به",
  "unitKilobyte": "{} كيلوبايت",
  "unitMegabyte": "{} ميغابايت",
  "unknownError": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  "updateAvailableMessage": "يتوفر إصدار جديد من التطبيق. يُنصح بالتحديث.",
  "updateAvailableTitle": "تحديث متاح",
  "updateNow": "تحديث",
  "userAccessEffective": "الصلاحيات الفعلية ({})",
  "userAccessOverrides": "الاستثناءات",
  "userAccessOverridesHint": "اضغط الصلاحية للتنقّل: وراثة ← سماح ← حظر. الحظر يغلب دائماً، وحظر العرض يسحب معه الإجراءات التي تحتاجه.",
  "userAccessRoles": "الأدوار",
  "userAccessTitle": "الصلاحيات",
  "users": "المستخدمون",
  "usersSubtitle": "تصفح قائمة المستخدمين",
  "verifyEmailCheckSpam": "لم يصلك شيء؟ تحقّق من مجلد البريد المزعج.",
  "verifyEmailCodeRequired": "أدخل الرمز المُرسَل إليك",
  "verifyEmailCta": "تأكيد",
  "verifyEmailHint": "أدخل الرمز",
  "verifyEmailResend": "إعادة إرسال الرمز",
  "verifyEmailResendIn": "إعادة الإرسال بعد {} ثانية",
  "verifyEmailResent": "أُرسل رمز جديد — الرمز السابق لم يعد صالحاً",
  "verifyEmailSubtitle": "أرسلنا رمزاً من ٨ أحرف إلى:",
  "verifyEmailSuccess": "تم تأكيد بريدك — طلبك الآن بانتظار موافقة الإدارة",
  "verifyEmailTitle": "أكّد بريدك الإلكتروني",
  "verifyEmailWhyBody": "لا يصل طلب تسجيلك إلى الإدارة قبل تأكيد عنوانك — هكذا لا يفتح أحد حساباً ببريد ليس له.",
  "verifyEmailWhyTitle": "لماذا هذه الخطوة؟",
  "wAgo": "أسبوع مضى",
  "warning": "تحذير",
  "welcomeBack": "مرحباً بك مرة أخرى",
  "welcomeGreeting": "أهلاً {}",
  "welcomeGreetingAnon": "أهلاً بك",
  "welcomeReady": "حسابك جاهز على هذا الجهاز",
  "yAgo": "سنة مضت",
  "yesterday": "أمس"
};
static const Map<String,dynamic> _en = {
  "SignUp": "Sign up",
  "accessControlDisabled": "Access control is turned off in this build",
  "accessNotEnforced": "This server is not enforcing permissions yet — grants are saved, but nothing is refused",
  "accountStatus": "Account status",
  "active": "Active",
  "activeDevicesCount": "Active devices: {count} of {max}",
  "activeDevicesSubtitle": "Where your account is signed in right now",
  "activeDevicesTitle": "Linked Devices",
  "addedAgo": "Added {time}",
  "alreadyHaveAccount": "Already have an account?",
  "appAppearance": "App appearance",
  "appInfo": "About",
  "appVersion": "App Version",
  "appearance": "Appearance",
  "apply": "Apply",
  "attachmentAdd": "Add photo",
  "attachmentCaptureFailed": "The photo could not be saved — please take it again",
  "attachmentDownloadFailed": "The file could not be downloaded — try again",
  "attachmentFailed": "Could not load — tap to retry",
  "attachmentLoading": "Loading…",
  "attachmentMissingLocally": "This file is no longer on the device — attach it again",
  "attachmentNotOnServer": "This file is no longer available",
  "attachmentOfflineUnavailable": "Not available offline",
  "attachmentOpenFailed": "No app on this device can open this file",
  "attachmentServerOnly": "This file is not on your device — tap to download it",
  "attachmentUnavailable": "Tap to reload",
  "attachments": "Attachments",
  "attachmentsEmpty": "No attachments yet",
  "backToLogin": "Back to Login",
  "badRequest": "Bad request",
  "cacheClearedSuccessfully": "Cache cleared successfully",
  "cacheError": "Cache error",
  "cancel": "Cancel",
  "cancelled": "Cancelled",
  "changePassword": "Change password",
  "checkYourEmail": "Check your email",
  "chooseFormat": "Choose a format",
  "clearCache": "Clear Cache",
  "clearCompleted": "Clear Completed",
  "clearFilters": "Clear filters",
  "clearedCompleted": "Cleared completed items",
  "completed": "Completed",
  "confirm": "Confirm",
  "confirmPassword": "Confirm Password",
  "continueGuest": "Continue as Guest",
  "createAccount": "Create one",
  "currentPassword": "Current password",
  "dAgo": "Day ago",
  "dataTransfer": "Import & export",
  "dataTransferSubtitle": "Download your data, or bring it in from a file",
  "daysAgo": "{days} days ago",
  "delete": "Delete",
  "deleteConfirmMessage": "Are you sure you want to delete this item?",
  "deleteConfirmTitle": "Confirm Delete",
  "deviceEmpty": "No active sessions",
  "deviceExpiresAt": "Expires",
  "deviceLastActive": "Last active",
  "deviceNoOthers": "No other devices",
  "deviceNotFound": "Device not found or already removed",
  "deviceRevoke": "Sign out",
  "deviceRevokeConfirmMessage": "It will have to sign in again. No other device is affected.",
  "deviceRevokeConfirmTitle": "Sign out this device?",
  "deviceRevokeDone": "Session ended",
  "deviceRevokeOthers": "Sign out other devices",
  "deviceRevokeOthersConfirmMessage": "Every other device will have to sign in again. This device stays signed in.",
  "deviceRevokeOthersConfirmTitle": "Sign out your other devices?",
  "deviceRevokeOthersDone": "{} sessions ended",
  "deviceSecurityNote": "Don't recognise a device? Sign it out and change your password.",
  "deviceSignedInAt": "Signed in",
  "deviceThisDevice": "This device",
  "deviceUnknown": "Unknown device",
  "dismiss": "Dismiss",
  "done": "Done",
  "dontHaveAccount": "Don't have an account?",
  "eMail": "E-mail",
  "edit": "Edit",
  "editProfile": "Edit Profile",
  "emailVerifiedNo": "Email not confirmed",
  "emailVerifiedYes": "Email confirmed",
  "enableNotifications": "Enable Notifications",
  "endOfList": "End of list",
  "error": "Error",
  "eventLogTitle": "Event Log",
  "exitAppMessage": "Are you sure you want to exit the application?",
  "exitAppTitle": "Exit App?",
  "exportAgain": "Export again",
  "exportClearAll": "Clear",
  "exportColumns": "Columns",
  "exportFilters": "Filters",
  "exportFiltersHint": "Leave empty to export everything",
  "exportFormat": "Format",
  "exportOpen": "Open",
  "exportPreparing": "Preparing your file…",
  "exportReadyTitle": "Your file is ready",
  "exportRowLimit": "Up to {} rows per export",
  "exportRun": "Export",
  "exportSelectAll": "Select all",
  "exportShare": "Share",
  "exportTitle": "Export",
  "feedbackStyle": "Feedback Style",
  "fieldRequired": "This field is required",
  "fileOpenExternal": "Open in another app",
  "fileOpenFailed": "No app on this device can open this file",
  "filePreview": "Preview",
  "filePreviewEmpty": "This file is empty",
  "filePreviewExternal": "Preview in another app",
  "filePreviewFailed": "Could not read this file",
  "filePreviewHeaderOnly": "Headers only — no data rows",
  "filePreviewRows": "{} rows",
  "filePreviewTruncated": "First {} rows",
  "fileReady": "File ready",
  "fileSave": "Save to device",
  "fileSaveFailed": "Could not save the file",
  "fileSaveHint": "Choose where to keep it",
  "fileSaved": "Saved",
  "fileShare": "Share",
  "filter": "Filter",
  "forbiddenAction": "You do not have permission to perform this action",
  "forgotPassword": "Forgot Password?",
  "forgotPasswordHint": "Enter your email and we'll send you a password reset link",
  "formValid": "Valid",
  "formatCsvHint": "Opens anywhere · easy to edit as text",
  "formatXlsxHint": "Keeps real dates and numbers · best for Excel",
  "fullNameOptional": "Full name (optional)",
  "hAgo": "H ago",
  "homeSubtitle": "Explore what the app can do",
  "importColumnExample": "e.g. {}",
  "importColumnsHint": "These are the only columns the file needs. Anything else is ignored.",
  "importColumnsTitle": "Columns you fill in",
  "importCommitting": "Importing…",
  "importConfirm": "Import {} rows",
  "importDeleteRow": "Delete row",
  "importDoneTitle": "Import finished",
  "importDownloadTemplate": "Download template",
  "importDuplicateOf": "Duplicate of line {}",
  "importEditedNotice": "You changed rows — re-check before importing",
  "importErrorsTruncated": "Showing the first {} problems",
  "importFailedRows": "{} failed",
  "importGridTab": "Data",
  "importInserted": "{} added",
  "importListTab": "Problems",
  "importNoRowsShown": "No rows to show",
  "importNothingValid": "No row in this file can be imported",
  "importNothingWritten": "Nothing has been saved yet",
  "importOnlyProblems": "Problems only ({})",
  "importOptional": "Optional",
  "importPickFile": "Choose a file",
  "importRecheck": "Re-check",
  "importRequired": "Required",
  "importReviewTitle": "Review before importing",
  "importRowLabel": "Row {}",
  "importRowsInvalid": "{} rows with problems",
  "importRowsTooMany": "The file is too large to edit here. Fix it in Excel and upload again.",
  "importRowsValid": "{} rows ready",
  "importShowingRows": "Showing {} of {} rows",
  "importSkipped": "{} skipped",
  "importStartOver": "Import another file",
  "importSystemColumns": "Filled in by the system: {}",
  "importTemplateReady": "Template downloaded",
  "importTitle": "Import",
  "importUnsupported": "This item cannot be imported",
  "importUpdated": "{} updated",
  "importValidating": "Checking your file…",
  "importWarnings": "{} rows will be skipped",
  "importWholeRow": "Whole row",
  "inactive": "Inactive",
  "info": "Info",
  "invalidEmailAddress": "Invalid email address",
  "invalidInput": "Invalid input",
  "invalidPassword": "Password required",
  "invalidPasswordLength": "The password must be at least 8 characters and at most 30 characters",
  "invalidPhone": "Invalid phone number",
  "justNow": "Just now",
  "language": "Language",
  "lastActive": "Last active: {date}",
  "lastName": "Last Name",
  "lastSeenAgo": {
    "now": "last seen just now",
    "minutes": "last seen {minutes} minutes ago",
    "hours": "last seen {hours} hours ago",
    "yesterday": "last seen yesterday",
    "days": "last seen {days} days ago",
    "week": "last seen a week ago",
    "weeks": "last seen {weeks} weeks ago",
    "month": "last seen a month ago",
    "months": "last seen {months} months ago",
    "longTime": "last seen a long time ago"
  },
  "later": "Later",
  "loadMore": "Load more",
  "loadMoreFailed": "Couldn't load more",
  "loading": "Loading",
  "loadingMore": "Loading more…",
  "logOut": "Log Out",
  "login": "Login",
  "loginDisabled": "Your account has been disabled",
  "loginPendingApproval": "Your account is awaiting admin approval",
  "loginRejected": "Your registration request was rejected",
  "loginSuspended": "Your account is temporarily suspended",
  "loginToYourAccount": "Log in to your account",
  "logoutConfirmMessage": "Are you sure you want to log out?",
  "logoutConfirmTitle": "Log Out?",
  "logoutPendingWorkMessage": "{count} change(s) have not reached the server yet. Signing out leaves them on this device, and only this account can send them. Sign out anyway?",
  "logoutPendingWorkTitle": "Unsent changes on this device",
  "lottieAnimations": "Lottie Animations",
  "maintenance": "Under Maintenance",
  "memberSince": "Member since",
  "minAgo": "Min ago",
  "moAgo": "Mo ago",
  "networkChecking": "Checking connection",
  "networkConnected": "Connected to the network",
  "newPassword": "New password",
  "noCompletedItems": "No completed items to clear",
  "noDataFound": "No data found",
  "noInternet": "No internet",
  "noInternetConnection": "No internet connection, try again later",
  "notFound": "Not found",
  "notPrimaryDevice": "Only the primary device can sign out other devices",
  "notSpecified": "Not specified",
  "notificationCenterClearAll": "Clear all",
  "notificationCenterClearConfirmMessage": "Every notification in this list will be deleted. This cannot be undone.",
  "notificationCenterClearConfirmTitle": "Clear all notifications?",
  "notificationCenterEmpty": "No notifications yet",
  "notificationCenterMarkAllRead": "Mark all as read",
  "notificationCenterTitle": "Notification Center",
  "notificationCenterUntitled": "Notification",
  "notifications": "Notifications",
  "offlineListHint": "Couldn't reach the server — check your connection and try again",
  "optimisticUpdates": "Optimistic Updates",
  "option": "Option",
  "overrideAllow": "Allow",
  "overrideDeny": "Deny",
  "overrideInherit": "Inherit",
  "parseDataError": "Response data error, please try again",
  "password": "Password",
  "passwordChangedSuccess": "Password changed",
  "passwordMismatch": "Passwords do not match",
  "passwordMustDiffer": "The new password must differ from the current one",
  "passwordValidationError": "The password must contain at least one number and at least one letter",
  "passwordWeak": "Weak password",
  "passwordsDoNotMatch": "The two passwords do not match",
  "permissionClearAll": "None",
  "permissionDenied": "Permission denied, please allow access",
  "permissionImplies": "Also grants: {}",
  "permissionLabelInferred": "Label guessed from the action name",
  "permissionManageHint": "Everything here, including actions added later",
  "permissionPermanentlyDenied": "Permission permanently denied, open App Settings to enable it",
  "permissionSelectAll": "All",
  "permissionStale": "No longer declared",
  "phone": "Phone Number",
  "primaryDeviceBadge": "Primary",
  "profile": "Profile",
  "queueSectionTitle": "Sync Queue",
  "quickAccess": "Quick Access",
  "reconnecting": "Reconnecting...",
  "registerCta": "Create account",
  "registerSubtitle": "It takes less than a minute",
  "registerSuccess": "Account created — confirm your email to continue",
  "registerTitle": "Create an account",
  "reset": "Reset",
  "resetCode": "Reset code",
  "resetCodeSentTo": "If {email} is registered with us, we have sent it a code",
  "resetLinkSentTo": "Reset link sent to",
  "resetPassword": "Reset password",
  "retry": "Retry",
  "retryAfterFewMinutes": "Try again in a few minutes.",
  "retryAfterLater": "Try again later.",
  "retryAfterUnderMinute": "Try again in less than a minute.",
  "revokeAllDevices": "Log out all devices",
  "revokeAllDevicesMessage": "All devices except this one will be logged out.",
  "revokeDeviceMessage": "Log out from \"{device}\"?",
  "revokeDeviceTitle": "Log out device",
  "roleActivate": "Reactivate",
  "roleCreate": "New role",
  "roleDeactivate": "Deactivate",
  "roleEditorReadOnly": "System roles cannot be edited — the deployment depends on them",
  "roleEditorTitle": "Permissions",
  "roleInactiveBadge": "Deactivated",
  "roleKeyHint": "Lower snake case — used in seeds and scripts, and never renamed",
  "roleKeyLabel": "Key",
  "roleMembers": "{} member(s)",
  "roleNameArLabel": "Name (Arabic)",
  "roleNameEnLabel": "Name (English)",
  "rolePermissionsCount": "{} permission(s)",
  "roleSaved": "Permissions updated",
  "roleStaleGrants": "{} grant(s) this server no longer declares",
  "roleSystemBadge": "System role",
  "rolesEmpty": "No roles yet",
  "rolesManageSubtitle": "Manage roles and who holds each permission",
  "rolesTitle": "Roles & permissions",
  "rollbackApplied": "Rolled Back!",
  "save": "Save",
  "screenComingSoon": "Not built yet",
  "screenComingSoonHint": "This screen is being built and will be available soon.",
  "security": "Security",
  "sendResetCode": "Send reset code",
  "serverError": "Server error",
  "serverUnreachable": "Could not reach the server. Your connection is working, but the server is not responding.",
  "serviceUnavailable": "The service is temporarily unavailable due to load or maintenance.",
  "sessionExpiredMessage": "Your session has ended. Please sign in again.",
  "sessionGuardBiometricReason": "Verify your identity to unlock the app",
  "sessionGuardConfirmPinTitle": "Confirm your PIN",
  "sessionGuardEnterPin": "Enter your PIN to unlock",
  "sessionGuardLockedTitle": "App Locked",
  "sessionGuardPinMismatch": "PINs don't match, try again",
  "sessionGuardSetupPinSubtitle": "You'll be asked for this PIN to unlock the app later",
  "sessionGuardSetupPinTitle": "Create a PIN",
  "sessionGuardUseBiometrics": "Use biometrics",
  "sessionGuardWrongPin": "Wrong PIN, try again",
  "sessionRevoked": "Your account was signed in on another device, ending this session.",
  "sessionTimedOut": "Session timed out",
  "settings": "Settings",
  "signIn": "Sign in",
  "simulateServerError": "Simulate Server Error",
  "simulatedOnline": "Simulated: Online — queue drains automatically",
  "somethingWrong": "Something went wrong! Please try again",
  "sortBy": "Sort by",
  "statusActive": "Active",
  "statusDisabled": "Disabled",
  "statusPendingVerification": "Pending Email Confirmation",
  "success": "Success",
  "superAdminBadge": "Full access",
  "syncPattern": "Sync Pattern",
  "syncQueue": "Sync Queue",
  "syncing": "Syncing...",
  "tabHome": "Home",
  "tabProfile": "Profile",
  "tabSettings": "Settings",
  "tapToFeel": "Tap to feel",
  "tapToSimulate": "Tap a failure to simulate",
  "templateReady": "Template ready",
  "testApiSimulatorSubtitle": "Pipeline · Layers · Timing",
  "testBlocStatesSubtitle": "Freezed · BlocConsumer · Transitions",
  "testLottieHint": "Replace icons with real Lottie files from LottieFiles.com",
  "themeDark": "Dark",
  "themeLight": "Light",
  "themeSystem": "System default",
  "thisDeviceActiveNow": "This device  •  Active now",
  "today": "Today",
  "tooManyRequests": "Too many attempts in a short time.",
  "transferDisabled": "Import & export is turned off in this build",
  "transferNoFormat": "No supported file format",
  "transferUnknownResource": "The server does not offer this item for transfer",
  "typeEmail": "Type your email",
  "typeFullName": "How should we address you?",
  "typography": "Typography",
  "unauthorised": "Unauthorised",
  "unitKilobyte": "{} KB",
  "unitMegabyte": "{} MB",
  "unknownError": "Something went wrong. Please try again.",
  "updateAvailableMessage": "A new version of the app is available. Updating is recommended.",
  "updateAvailableTitle": "Update available",
  "updateNow": "Update",
  "userAccessEffective": "Resolved permissions ({})",
  "userAccessOverrides": "Exceptions",
  "userAccessOverridesHint": "Tap a permission to cycle: inherit → allow → deny. A deny always wins, and denying a view also removes the actions that needed it.",
  "userAccessRoles": "Roles",
  "userAccessTitle": "Access",
  "users": "Users",
  "usersSubtitle": "Browse the user list",
  "verifyEmailCheckSpam": "Nothing arrived? Check your spam folder.",
  "verifyEmailCodeRequired": "Enter the code that was sent to you",
  "verifyEmailCta": "Confirm",
  "verifyEmailHint": "Enter the code",
  "verifyEmailResend": "Send a new code",
  "verifyEmailResendIn": "You can request another in {}s",
  "verifyEmailResent": "A new code was sent — the previous one no longer works",
  "verifyEmailSubtitle": "We sent an 8-character code to:",
  "verifyEmailSuccess": "Email confirmed — your request is now awaiting admin approval",
  "verifyEmailTitle": "Confirm your email",
  "verifyEmailWhyBody": "Your registration does not reach an administrator until your address is confirmed — so nobody can open an account with an email they do not own.",
  "verifyEmailWhyTitle": "Why this step?",
  "wAgo": "W ago",
  "warning": "Warning",
  "welcomeBack": "Welcome back",
  "welcomeGreeting": "Welcome, {}",
  "welcomeGreetingAnon": "Welcome",
  "welcomeReady": "Your account is ready on this device",
  "yAgo": "Y ago",
  "yesterday": "Yesterday"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
