/// DO NOT EDIT THIS FILE MANUALLY
/// Generated on: 2026-06-23T11:39:10.031689
/// Run: dart run scripts/sync_fonts.dart to regenerate
///
class AppFontFamilies {
  const AppFontFamilies._();

  /// Weights: 400, 500, 700
  static const String itfQomraArabic = 'itfQomraArabic';

}
