import 'package:app_template/Features/notes/domain/entities/note.dart';

/// Wire shape of a note. Raw types only — dates stay `String` here and are
/// converted in [toEntity], so a malformed timestamp fails in one known place
/// rather than wherever the entity is first read.
class NoteModel {
  const NoteModel({
    required this.id,
    required this.title,
    this.body,
    required this.createdAt,
    required this.updatedAt,
    required this.version,
    required this.isDeleted,
  });

  /// A **uuid**, generated by whoever created the note — the client when the
  /// note was written offline, the server otherwise.
  ///
  /// It was a server-assigned `int` until the sync contract landed. A row
  /// created with no network has to have an identity the moment it exists: it
  /// is displayed, edited, and possibly deleted before any server sees it, and
  /// an id that arrives later would have to be back-patched everywhere the row
  /// was already referenced.
  final String id;
  final String title;
  final String? body;
  final String createdAt;
  final String updatedAt;

  /// Server-incremented on every write. Sent back on an edit to make it
  /// conditional; see `notes.dto.ts` for what a mismatch answers.
  final int version;

  /// A tombstone rather than a note. Only ever `true` on a row that arrived
  /// through a delta pull — the ordinary list endpoints filter them out.
  final bool isDeleted;

  factory NoteModel.fromJson(Map<String, dynamic> json) => NoteModel(
        id: json['id'] as String? ?? '',
        title: json['title'] as String? ?? '',
        body: json['body'] as String?,
        createdAt: json['created_at'] as String? ?? '',
        updatedAt: json['updated_at'] as String? ?? '',
        // Defaults matching the server's, so a response predating the sync
        // contract still parses instead of blanking a list.
        version: json['version'] as int? ?? 1,
        isDeleted: json['is_deleted'] as bool? ?? false,
      );

  /// Rebuilds the wire shape from an entity — the direction the sync module
  /// needs, and the one an online-only client never does.
  ///
  /// A queued write has to survive an app restart, so it is stored as JSON and
  /// replayed later. That JSON must be **the shape the server accepts**, which
  /// is this class's whole job; serialising the entity directly would invent a
  /// second wire format that nothing validates.
  factory NoteModel.fromEntity(Note note) => NoteModel(
        id: note.id,
        title: note.title,
        body: note.body,
        createdAt: note.createdAt.toIso8601String(),
        updatedAt: note.updatedAt.toIso8601String(),
        version: note.version,
        isDeleted: note.isDeleted,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'body': body,
        'created_at': createdAt,
        'updated_at': updatedAt,
        'version': version,
        'is_deleted': isDeleted,
      };

  Note toEntity() => Note(
        id: id,
        title: title,
        body: body,
        // DateTime(2000) rather than a throw: one unreadable timestamp must not
        // blank a whole page of notes.
        createdAt: DateTime.tryParse(createdAt) ?? DateTime(2000),
        updatedAt: DateTime.tryParse(updatedAt) ?? DateTime(2000),
        version: version,
        isDeleted: isDeleted,
      );
}
