// ignore_for_file: avoid_print
/// يقرأ flavor_settings.json ويُحدِّث تلقائياً:
///   1. android/app/flavorizr.gradle.kts        — applicationId لكل flavor
///   2. android/app/src/{f}/res/values/strings.xml — اسم التطبيق لكل flavor
///   3. flutter_launcher_icons-{f}.yaml          — ملفات إعداد الأيقونات
///   4. يُشغِّل flutter_launcher_icons لكل flavor
///   5. .vscode/launch.json                      — إعدادات تشغيل VSCode
///
/// تشغيل من جذر المشروع:
///   dart run scripts/sync_flavors.dart           — إعداد الـ flavors
///   dart run scripts/sync_flavors.dart --reset   — إزالة كل شيء تابع للـ flavors
library;

import 'dart:convert';
import 'dart:io';

// ── Constants ─────────────────────────────────────────────────────────────────

const _settingsFile = 'flavor_settings.json';

// ── Entry point ───────────────────────────────────────────────────────────────

void main(List<String> args) async {
  if (args.contains('--reset')) {
    _reset();
    return;
  }

  print('\n🚀  sync_flavors — starting...\n');

  // 1. Load & validate flavor_settings.json
  final settings = _loadSettings();
  final flavors = settings['flavors'] as Map<String, dynamic>;

  print('📋  Flavors found: ${flavors.keys.join(', ')}\n');

  // 2. Validate icon files exist before doing any work
  _validateIcons(flavors);

  // 3. Inject productFlavors into android/app/build.gradle.kts
  _updateBuildGradle(flavors);

  // 4. Create per-flavor strings.xml (app name — most reliable approach)
  _updateAndroidStrings(flavors);

  // 5. Generate flutter_launcher_icons-{flavor}.yaml files
  _generateIconYamls(flavors);

  // 6. Run flutter_launcher_icons for each flavor
  await _runIconGeneration(flavors);

  // 7. Generate .vscode/launch.json
  _generateLaunchJson(flavors);

  print('\n✅  sync_flavors done.\n');
  print('─────────────────────────────────────────────────────────────────');
  print('  Next: clean & rebuild the app to see the new icons.');
  print('  flutter clean && flutter pub get');
  print('─────────────────────────────────────────────────────────────────\n');
}

// ── Step 1 — load settings ────────────────────────────────────────────────────

Map<String, dynamic> _loadSettings() {
  final file = File(_settingsFile);
  if (!file.existsSync()) {
    _error('$_settingsFile not found. Run from project root.');
    exit(1);
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

// ── Step 2 — validate icons ───────────────────────────────────────────────────

void _validateIcons(Map<String, dynamic> flavors) {
  var missing = false;
  for (final entry in flavors.entries) {
    final cfg = entry.value as Map<String, dynamic>;
    final path = cfg['iconPath'] as String;
    if (!File(path).existsSync()) {
      _warn('Icon not found for "${entry.key}": $path');
      missing = true;
    }
  }
  if (missing) {
    print('''
⚠️  One or more icon files are missing.
    Place 1024×1024 PNG files at the paths listed in flavor_settings.json,
    then re-run this script.
    Icon generation will be skipped for missing flavors.
''');
  }
}

// ── Step 3 — inject productFlavors into build.gradle.kts ─────────────────────

void _updateBuildGradle(Map<String, dynamic> flavors) {
  final file = File('android/app/build.gradle.kts');
  if (!file.existsSync()) {
    _error('android/app/build.gradle.kts not found.');
    return;
  }

  final buf = StringBuffer();
  buf.writeln('    // BEGIN FLAVORS — auto-generated by: dart run scripts/sync_flavors.dart');
  buf.writeln('    flavorDimensions += "app"');
  buf.writeln('    productFlavors {');
  for (final entry in flavors.entries) {
    final name = entry.key;
    final id   = (entry.value as Map<String, dynamic>)['applicationId'] as String;
    buf.writeln('        create("$name") {');
    buf.writeln('            dimension = "app"');
    buf.writeln('            applicationId = "$id"');
    buf.writeln('        }');
  }
  buf.writeln('    }');
  buf.write('    // END FLAVORS');

  final content  = file.readAsStringSync();
  final replaced = _replaceBetweenMarkers(content, buf.toString());
  file.writeAsStringSync(replaced);
  print('🤖  Updated productFlavors in android/app/build.gradle.kts');
}

String _replaceBetweenMarkers(String content, String newBlock) {
  const begin = '// BEGIN FLAVORS';
  const end   = '// END FLAVORS';
  final iBegin = content.indexOf(begin);
  final iEnd   = content.indexOf(end);

  // Markers found — replace between them (normal case)
  if (iBegin != -1 && iEnd != -1) {
    return content.substring(0, iBegin) +
        newBlock +
        content.substring(iEnd + end.length);
  }

  // Markers missing (e.g. after --reset) — auto-insert before android {} closing brace
  final flutterStart = content.indexOf('\nflutter {');
  if (flutterStart == -1) {
    _warn('Cannot find `flutter {` in build.gradle.kts — flavors not added.');
    return content;
  }
  final androidClose = content.lastIndexOf('}', flutterStart);
  if (androidClose == -1) {
    _warn('Cannot find android {} closing brace — flavors not added.');
    return content;
  }
  print('🔧  Markers missing — auto-inserting productFlavors block.');
  return '${content.substring(0, androidClose)}\n\n$newBlock\n${content.substring(androidClose)}';
}

// ── Step 4 — per-flavor strings.xml ──────────────────────────────────────────

void _updateAndroidStrings(Map<String, dynamic> flavors) {
  for (final entry in flavors.entries) {
    final flavor = entry.key;
    final cfg    = entry.value as Map<String, dynamic>;
    final name   = cfg['displayName'] as String;

    final dir = Directory('android/app/src/$flavor/res/values');
    dir.createSync(recursive: true);

    File('${dir.path}/strings.xml').writeAsStringSync(
      '<?xml version="1.0" encoding="utf-8"?>\n'
      '<resources>\n'
      '    <string name="app_name">$name</string>\n'
      '</resources>\n',
    );
    print('📝  strings.xml [$flavor] → "$name"');
  }
}

// ── Step 5 — flutter_launcher_icons yaml ─────────────────────────────────────

void _generateIconYamls(Map<String, dynamic> flavors) {
  for (final entry in flavors.entries) {
    final flavor = entry.key;
    final cfg    = entry.value as Map<String, dynamic>;
    final icon   = cfg['iconPath'] as String;
    final bg     = cfg['adaptiveIconBackground'] as String? ?? '#FFFFFF';

    if (!File(icon).existsSync()) return; // already warned above

    final yaml = '''flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "$icon"
  min_sdk_android: 21
  adaptive_icon_background: "$bg"
  adaptive_icon_foreground: "$icon"
''';

    File('flutter_launcher_icons-$flavor.yaml').writeAsStringSync(yaml);
    print('📄  flutter_launcher_icons-$flavor.yaml generated');
  }
}

// ── Step 6 — run flutter_launcher_icons ──────────────────────────────────────

Future<void> _runIconGeneration(Map<String, dynamic> flavors) async {
  print('');
  for (final flavor in flavors.keys) {
    final yamlFile = 'flutter_launcher_icons-$flavor.yaml';
    if (!File(yamlFile).existsSync()) {
      _warn('Skipping icon generation for $flavor — yaml not found.');
      continue;
    }

    print('🖼   Generating icons for "$flavor"...');
    final result = await Process.run(
      'dart',
      ['run', 'flutter_launcher_icons', '-f', yamlFile],
      runInShell: true,
    );

    if (result.exitCode == 0) {
      print('✅  Icons for "$flavor" done.');
    } else {
      _error('Icon generation failed for "$flavor":\n${result.stderr}');
    }
  }
}

// ── Step 7 — .vscode/launch.json ─────────────────────────────────────────────

void _generateLaunchJson(Map<String, dynamic> flavors) {
  final configs = <Map<String, dynamic>>[];

  for (final flavor in flavors.keys) {
    configs.add({
      'name':        '${flavor.toUpperCase()} · Debug',
      'request':     'launch',
      'type':        'dart',
      'flutterMode': 'debug',
      'program':     'lib/main.dart',
      'args': [
        '--flavor', flavor,
        '--dart-define=FLAVOR=$flavor',
        '--dart-define-from-file=.env.$flavor.json',
      ],
    });
  }

  Directory('.vscode').createSync(recursive: true);
  File('.vscode/launch.json').writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert({'version': '0.2.0', 'configurations': configs})}\n',
  );
  print('🚀  Generated .vscode/launch.json (${configs.length} configs)');
}

// ── Reset ─────────────────────────────────────────────────────────────────────

void _reset() {
  print('\n🧹  sync_flavors --reset — removing all flavor artifacts...\n');

  // 1. Per-flavor source directories (strings.xml, icons…)
  for (final flavor in ['dev', 'staging', 'prod']) {
    _deleteDir('android/app/src/$flavor');
    _deleteFile('flutter_launcher_icons-$flavor.yaml');
  }

  // 2. Clear productFlavors block from build.gradle.kts (between markers)
  final buildFile = File('android/app/build.gradle.kts');
  if (buildFile.existsSync()) {
    const begin = '// BEGIN FLAVORS';
    const end   = '// END FLAVORS';
    final content = buildFile.readAsStringSync();
    final iBegin  = content.indexOf(begin);
    final iEnd    = content.indexOf(end);
    if (iBegin != -1 && iEnd != -1) {
      final cleaned = '${content.substring(0, iBegin).trimRight()}\n${content.substring(iEnd + end.length).trimLeft()}';
      buildFile.writeAsStringSync(cleaned);
      print('✏️   Cleared productFlavors from android/app/build.gradle.kts');
    }
  }

  // 3. .vscode/launch.json
  _deleteFile('.vscode/launch.json');

  print('\n✅  Reset done. Project is back to plain Flutter (no flavors).');
  print('   Run: flutter clean && flutter pub get\n');
}

void _deleteFile(String path) {
  final f = File(path);
  if (f.existsSync()) {
    f.deleteSync();
    print('🗑   Deleted $path');
  }
}

void _deleteDir(String path) {
  final d = Directory(path);
  if (d.existsSync()) {
    d.deleteSync(recursive: true);
    print('🗑   Deleted $path/');
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

void _warn(String msg)  => print('⚠️   $msg');
void _error(String msg) => print('❌   $msg');
